
[project]
name = "pd"
version = "0.1.3"
description = "PD - analysis of unit injectors"
requires-python = ">=3.10"
authors = [
    { name = "Mateusz Jamr√≥z" }
]

[project.scripts]
pd = "pd.__main__:main"

[tool.setuptools.packages.find]
where = ["."]
